# Supabase Project Configuration
project_id = "${SUPABASE_PROJECT_REF}"

[auth]
# Configuração personalizada para a autenticação
site_url = "${VITE_SITE_URL}"
additional_redirect_urls = [
  "${VITE_SITE_URL}/*",
  "http://localhost:3000/*"
]

# Configuração do provedor de e-mail personalizado
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Variáveis de ambiente para as Edge Functions
[functions.custom-email]
verify_jwt = false

# Environment variables are configured via:
# 1. Vercel Dashboard for production
# 2. .env.local for development
# 3. supabase/setup-env.sh for Edge Functions