project_id = "hpovwcaskorzzrpphgkc"

[auth]
# Configuração personalizada para a autenticação
site_url = "https://saa-s-agent.vercel.app"
additional_redirect_urls = [
  "https://saa-s-agent.vercel.app/*",
  "http://localhost:3000/*",
  "http://localhost:8080/*"
]

# Configuração do provedor de e-mail personalizado
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Variáveis de ambiente para as Edge Functions
[functions.custom-email]
verify_jwt = false

# As variáveis de ambiente da função precisam ser configuradas após o deploy
# usando o comando supabase secrets set