
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_CONFIG } from '../../config/environment';

// Use centralized environment configuration
const SUPABASE_URL = SUPABASE_CONFIG.url;
const SUPABASE_PUBLISHABLE_KEY = SUPABASE_CONFIG.anonKey;

// Validate required configuration
if (!SUPABASE_URL) {
  throw new Error('SUPABASE_URL is required but not configured');
}

// FALLBACK TEMPORÁRIO para debug - permitir carregar mesmo com chave vazia
let effectiveAnonKey = SUPABASE_PUBLISHABLE_KEY;
if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.trim() === '') {
  console.error('❌ SUPABASE_ANON_KEY não está configurada!');
  console.error('💡 Usando fallback temporário para debug');
  console.error('🔧 Certifique-se de que VITE_SUPABASE_ANON_KEY está no arquivo .env');
  
  // Usar uma chave falsa temporariamente para permitir debug
  effectiveAnonKey = 'debug-mode-key';
}

export const supabase = createClient<Database>(SUPABASE_URL, effectiveAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
