
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables if available, otherwise fallback to constants
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://hpovwcaskorzzrpphgkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "process.env.SUPABASE_ANON_KEY || "";

// Define backend environment variables
// STRIPE_SECRET_KEY is set in the Supabase dashboard

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
